[package]
name = "kalc"
description = "a complex numbers, 2d/3d graphing, arbitrary precision, vector/matrix, cli calculator with real-time output and support for units"
license = "GPL-3.0-only"
authors = ["bgkillas <mswalhelm@gmail.com>"]
readme = "README.md"
keywords = ["cli", "calculator"]
categories = ["command-line-interface", "command-line-utilities", "mathematics"]
repository = "https://github.com/bgkillas/kalc"
rust-version = "1.85.0"
version = "1.4.2"
edition = "2024"

[profile.release]
lto = true
strip = true
panic = "abort"

[profile.dev]
opt-level = 1

[dependencies]
fastrand = "2.0.2"
rug = "1.24.1"
crossterm = "0.28.1"
dirs = "6.0.0"
rayon = "1.10.0"

[target.'cfg(not(unix))'.dependencies]
term_size = "0.3.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.169"

[dependencies.gmp-mpfr-sys]
version = "1.6.4"
features = ["force-cross"]